development:
  host: localhost
  port: 27017
  database: zubr_dev
  logfile: development.log

production:
  host: localhost
  port: 27017
  database: zubr_prod
  logfile: production.log

environment: development
